# Generated by Django 5.2.1 on 2025-05-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('f_name', models.CharField(max_length=255, verbose_name='نام')),
                ('l_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('status', models.CharField(choices=[('NEW', 'جدید'), ('INP', 'درحال برسی'), ('COM', 'برسی شده'), ('ARC', 'بایگانی شده')], default='NEW', max_length=3)),
                ('is_ignored', models.BooleanField(default=True)),
                ('is_readed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تماس فوری',
                'verbose_name_plural': 'تماس های فوری',
                'ordering': ['-created_at'],
            },
        ),
    ]
