# Generated by Django 5.2.1 on 2025-06-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_ignored',
            field=models.BooleanField(default=True, verbose_name='نادیده گرفته شده؟'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_readed',
            field=models.BooleanField(default=False, verbose_name='خوانده شده؟'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('NEW', 'جدید'), ('INP', 'درحال برسی'), ('COM', 'برسی شده'), ('ARC', 'بایگانی شده')], default='NEW', max_length=3, verbose_name='وضعیت درخواست'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
    ]
