# Generated by Django 5.2.1 on 2025-05-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('image', models.FileField(upload_to='Cranes/images/', verbose_name='تصویر')),
                ('conetnt', models.TextField(blank=True, null=True, verbose_name='محتوا')),
            ],
            options={
                'verbose_name': 'جرثقیل',
                'verbose_name_plural': 'جرثقیل ها',
            },
        ),
    ]
