# Generated by Django 5.2.1 on 2025-06-01 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('image', models.FileField(upload_to='Cranes/images/', verbose_name='تصویر')),
                ('conetnt', models.TextField(blank=True, null=True, verbose_name='محتوا')),
                ('views', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
            ],
            options={
                'verbose_name': 'جرثقیل',
                'verbose_name_plural': 'جرثقیل ها',
            },
        ),
        migrations.CreateModel(
            name='CraneContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True, verbose_name='عنوان')),
                ('content', models.TextField(blank=True, null=True, verbose_name='محتوا')),
                ('image', models.FileField(blank=True, null=True, upload_to='Cranes/Content/images/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('crane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crane_contents', to='Cranes.crane', verbose_name='جرثقیل')),
            ],
            options={
                'verbose_name': 'محتوا',
                'verbose_name_plural': 'محتوا ها',
            },
        ),
        migrations.CreateModel(
            name='CraneImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='Cranes/Images/images/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('crane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crane_images', to='Cranes.crane', verbose_name='جرثقیل')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصویر ها',
            },
        ),
        migrations.CreateModel(
            name='CraneRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('f_name', models.CharField(max_length=255, verbose_name='نام')),
                ('l_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('status', models.CharField(choices=[('N', 'جدید'), ('P', 'درحال برسی'), ('C', 'تکمیل شده'), ('A', 'بایگانی شده'), ('V', 'تایید شده'), ('R', 'رد شده')], default='N', max_length=3, verbose_name='وضعیت درخواست')),
                ('is_ignored', models.BooleanField(default=True, verbose_name='نادیده گرفته شده؟')),
                ('is_readed', models.BooleanField(default=False, verbose_name='خوانده شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('crane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crane_requests', to='Cranes.crane', verbose_name='جرثقیل')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست ها',
                'ordering': ['-created_at'],
            },
        ),
    ]
