# Generated by Django 5.2.1 on 2025-05-31 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cranes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraneContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True, verbose_name='عنوان')),
                ('content', models.TextField(blank=True, null=True, verbose_name='محتوا')),
                ('image', models.FileField(blank=True, null=True, upload_to='Cranes/Content/images/', verbose_name='تصویر')),
                ('crane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crane_contents', to='Cranes.crane', verbose_name='جرثقیل')),
            ],
            options={
                'verbose_name': 'محتوا',
                'verbose_name_plural': 'محتوا ها',
            },
        ),
    ]
