# Generated by Django 5.2.1 on 2025-06-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cranes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crane',
            old_name='conetnt',
            new_name='content',
        ),
    ]
