# Generated by Django 5.2.1 on 2025-07-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cranes', '0002_rename_conetnt_crane_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crane',
            name='name',
            field=models.CharField(max_length=250, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='crane',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='cranecontent',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان'),
        ),
    ]
