# Generated by Django 5.2.1 on 2025-05-31 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cranes', '0002_cranecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraneImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='Cranes/Images/images/', verbose_name='تصویر')),
                ('crane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crane_images', to='Cranes.crane', verbose_name='جرثقیل')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصویر ها',
            },
        ),
    ]
