# Generated by Django 5.2.1 on 2025-05-31 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cranes', '0003_craneimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraneRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('f_name', models.CharField(max_length=255, verbose_name='نام')),
                ('l_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('status', models.CharField(choices=[('N', 'جدید'), ('P', 'درحال برسی'), ('C', 'تکمیل شده'), ('A', 'بایگانی شده'), ('V', 'تایید شده'), ('R', 'رد شده')], default='N', max_length=3)),
                ('is_ignored', models.BooleanField(default=True)),
                ('is_readed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crane_requests', to='Cranes.crane', verbose_name='جرثقیل')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست ها',
                'ordering': ['-created_at'],
            },
        ),
    ]
