# Generated by Django 5.2.1 on 2025-06-01 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cranes', '0004_cranerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='crane',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crane',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AddField(
            model_name='crane',
            name='views',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AddField(
            model_name='cranecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cranecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AddField(
            model_name='craneimages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='craneimages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='cranerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='cranerequest',
            name='is_ignored',
            field=models.BooleanField(default=True, verbose_name='نادیده گرفته شده؟'),
        ),
        migrations.AlterField(
            model_name='cranerequest',
            name='is_readed',
            field=models.BooleanField(default=False, verbose_name='خوانده شده؟'),
        ),
        migrations.AlterField(
            model_name='cranerequest',
            name='status',
            field=models.CharField(choices=[('N', 'جدید'), ('P', 'درحال برسی'), ('C', 'تکمیل شده'), ('A', 'بایگانی شده'), ('V', 'تایید شده'), ('R', 'رد شده')], default='N', max_length=3, verbose_name='وضعیت درخواست'),
        ),
        migrations.AlterField(
            model_name='cranerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
    ]
