# Generated by Django 5.2.1 on 2025-06-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='نام و نام خانوادگی'),
            preserve_default=False,
        ),
    ]
