# Generated by Django 5.2.1 on 2025-05-31 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('content', models.TextField(blank=True, null=True, verbose_name='محتوا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blogs/content/images/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_contents', to='Blogs.blog', verbose_name='بلاگ')),
            ],
            options={
                'verbose_name': 'محتوای بلاگ',
                'verbose_name_plural': 'محتوا های بلاگ ها',
            },
        ),
    ]
