# Generated by Django 5.2.1 on 2025-05-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='جواب')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوال های متداول',
            },
        ),
    ]
